# The file is automatically generated by Ansible by running the
# cluster.yml playbook.
[localhost]
127.0.0.1 ansible_connection=local ansible_python_interpreter="/usr/bin/python3"

[controllers]
rancher1 ansible_ssh_host=${ip[0].address}

[agents]
rancher2 ansible_ssh_host=${ip[1].address}
rancher3 ansible_ssh_host=${ip[2].address}

[nodes:children]
controllers
agents

[rke_cluster:children]
controllers
agents

[all:vars]
ansible_ssh_port=22
ansible_user='ubuntu'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=${key}
ansible_python_interpreter="/usr/bin/python3"

